In [2]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv('Dataset.csv')
df.sample(5, random_state=12)

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
92,52,1,2,138,223,0,1,169,0,0.0,2,4,2,1
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2,1
233,64,1,0,120,246,0,0,96,1,2.2,0,1,2,0
243,57,1,0,152,274,0,1,88,1,1.2,1,1,3,0

In [28]:
X = np.array(df[['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh', 'exng']])
y = np.array(df['output'])
print(f'x :\n{X[:5]}\ny :\n{y[:5]}')

x :
[[ 63   1   3 145 233   1   0 150   0]
 [ 37   1   2 130 250   0   1 187   0]
 [ 41   0   1 130 204   0   0 172   0]
 [ 56   1   1 120 236   0   1 178   0]
 [ 57   0   0 120 354   0   1 163   1]]
y :
[1 1 1 1 1]

In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=12
)

In [31]:
print(x_train.shape, end=' ')
print(y_train.shape)
print(x_test.shape, end=' ')
print(y_test.shape)

(242, 9) (242,)
(61, 9) (61,)

In [75]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

accuracy = []
for n in range(1, 10):
    model = KNeighborsClassifier(n_neighbors=n)
    model.fit(x_train, y_train)
    y_hat = model.predict(x_test)
    accuracy.append(accuracy_score(y_test, y_hat))
    
result = pd.DataFrame({'K':range(1, 10), 'Accuracy':accuracy})
result

   K  Accuracy
0  1  0.491803
1  2  0.491803
2  3  0.557377
3  4  0.590164
4  5  0.655738
5  6  0.622951
6  7  0.622951
7  8  0.672131
8  9  0.688525

In [63]:
model = KNeighborsClassifier(n_neighbors=9, weights='distance')
model.fit(x_train, y_train)
y_hat = model.predict(x_test)
print(f'accuracy with k(9) and weights(distance) is = {accuracy_score(y_test, y_hat)}')

accuracy with k(9) and weights(distance) is = 0.639344262295082